# Generated by Django 2.1.5 on 2020-07-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
    ]
