# Generated by Django 2.1.5 on 2020-07-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificateApp', '0002_profile_is_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_editable',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='edit_reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='request_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='edit_reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='request_edit',
            field=models.BooleanField(default=False),
        ),
    ]
