# Generated by Django 2.1.5 on 2020-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificateApp', '0003_auto_20200707_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='is_editable',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_editable',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=10),
        ),
    ]
