# Generated by Django 2.1.1 on 2020-07-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificateApp', '0005_certificateconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
